name: Generate dbt model and Denodo views

on:
  push:
    branches:
      - main

jobs:
  generate_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl snowflake-connector-python pyyaml

      - name: Find newly added YAML files and generate views
        run: |
          echo "🔍 Looking for newly added YAML files..."
          # added_files=$(git diff --name-only --diff-filter=A HEAD~1 HEAD | grep '^configs/.*\.yaml$' || true)
          added_files=$(git diff --name-only HEAD~1 HEAD | grep '\.yaml$' || true)

          if [ -z "$added_files" ]; then
            echo "✅ No new YAML files added. Skipping generation."
            exit 0
          fi

          echo "🆕 New YAML files detected:"
          echo "$added_files"

          for file in $added_files; do
            table_name=$(basename "$file" .yaml)
            echo "⚙️ Processing: $table_name"

            python scripts/generate_dbt_model.py "$table_name"
            python scripts/generate_denodo_base.py "$table_name"
            python scripts/generate_denodo_clean.py "$table_name"
          done

      - name: Commit and push generated files
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add .
          git commit -m "✅ Generated dbt and Denodo views for newly added tables" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref_name }}
