name: Update Column Descriptions & Views

on:
  push:
    paths:
      - 'configs/*.yaml'

jobs:
  update-descriptions:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch full git history
        run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install snowflake-connector-python pyyaml

      - name: Find modified YAML files and run scripts
        run: |
          echo "🔍 Checking for modified YAML files in configs/..."
          changed_files=$(git diff --name-only --diff-filter=M HEAD~1 HEAD | grep '\.yaml$' || true)
          
          if [ -z "$changed_files" ]; then
            echo "✅ No YAML files changed. Skipping job."
            exit 0
          fi

          echo "📝 Modified YAML files:"
          echo "$changed_files"

          for file in $changed_files; do
            table_name=$(basename "$file" .yaml)
            echo "🔄 Processing table: $table_name from $file"

            python scripts/update_column_descriptions.py "$file" "configs/template_config.json"
            python scripts/generate_dbt_model.py "$table_name"
            python scripts/generate_denodo_base.py "$table_name"
            python scripts/generate_denodo_clean.py "$table_name"
          done
