name: Update Column Descriptions & Views

on:
  push:
    paths:
      - 'configs/*.yaml'

jobs:
  update-descriptions:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch full git history
        run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install snowflake-connector-python pyyaml

      - name: Identify modified YAML files
        id: changed_yaml
        run: |
          files=$(git diff --name-only origin/main...HEAD | grep 'configs/.*\.yaml$' || true)
          echo "files=$files" >> $GITHUB_OUTPUT

      - name: Show modified YAML files
        run: echo "📝 Modified YAML files: ${{ steps.changed_yaml.outputs.files }}"

      - name: Run scripts for each modified YAML
        run: |
          for file in ${{ steps.changed_yaml.outputs.files }}; do
            table_name=$(basename "$file" .yaml)
            echo "🔄 Processing table: $table_name from $file"
            python scripts/update_column_descriptions.py "$file" "configs/template_config.json"
            python scripts/generate_dbt_model.py "$table_name"
            python scripts/generate_denodo_base.py "$table_name"
            python scripts/generate_denodo_clean.py "$table_name"
          done
