name: Update Snowflake table column description and generate dbt model and Denodo views

on:
  push:
    branches:
      - main

jobs:
  update-descriptions:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch the last 2 commits to allow comparison

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install snowflake-connector-python pyyaml

      - name: Identify modified YAML files
        id: changed_yaml
        run: |
          files=$(git diff --name-only HEAD~1 HEAD || echo "")
          echo "files=$files" >> $GITHUB_ENV
          echo "Modified YAMLs: $files"

      - name: Run scripts for each modified YAML
        if: env.files != ''
        run: |
          for file in $files; do
            table_name=$(basename "$file" .yaml)
            echo "🔄 Processing table: $table_name"
            python utility/update_column_descriptions.py "$file" "utility/config.json"
            python utility/Generate_BaseView.py "$table_name"
            python utility/Generate_CleanView.py "$table_name"
          done

      - name: No YAML files modified
        if: env.files == ''
        run: echo "⚠️ No modified YAML files found. Skipping processing."
